spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poker_db
    username: wata
    password: Pa_2word
    driver-class-name: com.mysql.cj.jdbc.Driver



  security:
    user:
      name: wata
      password: wata